# Generated by Django 5.0.1 on 2024-01-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial1', '0002_item_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='appoptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
